spring:
    application:
        name: smartsteve

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    ai:
        openai:
            api-key: ${HCAI_API_KEY}
            embedding:
                base-url: https://ai.hackclub.com/proxy
                options:
                    model: openai/text-embedding-3-small
                    dimensions: 1536
        vectorstore:
            pgvector:
                initialize-schema: true
                index-type: HNSW

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

    h2:
        console:
            enabled: true
            path: /h2-console


logging:
    level:
        org.springframework.web.client.RestClient: DEBUG
        org.springframework.ai: DEBUG

google:
    api:
        key: ${GOOGLE_API_KEY}

hcai:
    api:
        key: ${HCAI_API_KEY}

hcsearch:
    api:
        key: ${HCSEARCH_API_KEY}

groq:
    api:
        key: ${GROQ_API_KEY}
