spring:
    application:
        name: smartsteve

    datasource:
        url: jdbc:h2:file:./data/database
        driverClassName: org.h2.Driver
        username: sa
        password: password

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true

    h2:
        console:
            enabled: true
            path: /h2-console


google:
    api:
        key: ${GOOGLE_API_KEY}

hcai:
    api:
        key: ${HCAI_API_KEY}

hcsearch:
    api:
        key: ${HCSEARCH_API_KEY}
